//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntingRadar.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuntingRadar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ##### 2.0 重生之境狩猎 ##################################
        ///白鬼鼠王,B
        ///击刺魔蜂索菲,B
        ///君王鬼蜻蜓,B
        ///天玑巨熊,B
        ///阴沟毒液,B
        ///奥弗杰恩,B
        ///加特林针鼹,B
        ///死灰复燃的阿尔宾,B
        ///永恒不灭的菲兰德副耀士,B
        ///花林女郎,B
        ///宽耳凶蝠,B
        ///血腥玛丽,B
        ///暗盔魔蟹,B
        ///米腊德罗斯蜂鸟,B
        ///巫刻猎鹫,B
        ///纳乌尔,B
        ///水蛭王,B
        ///
        ///弗内乌斯,A
        ///千眼凝胶,A
        ///盖得,A
        ///尾宿蛛蝎,A
        ///阿列刻特利昂,A
        ///花舞仙人刺,A
        ///玛赫斯,A
        ///札尼戈,A
        ///菲兰德的遗火,A
        ///&quot;丑男子 沃迦加&quot;,A
        ///乌克提希,A
        ///魔导地狱爪,A
        ///纳恩,A
        ///玛贝利,A
        ///角祖,A
        ///马拉克,A
        ///库雷亚,A
        ///
        ///雷德罗巨蛇,S
        ///乌尔伽鲁,S
        ///夺心魔,S
        ///千竿口花希达,S
        ///虚无探索者,S
        ///布隆特斯,S
        ///巴拉乌尔,S
        ///努纽努维,S
        ///蚓螈巨虫,S
        ///护土精灵,S
        ///咕尔呱洛斯,S
        ///伽洛克,S
        ///火愤牛,S
        ///南迪,S
        ///牛头黑神,S
        ///萨法特,S
        ///阿格里帕,S
        ///
        ///
        ///##### 3.0 苍穹之禁城狩猎 ##################################
        ///阿尔提克,B
        ///克鲁泽,B
        ///骨颌彗星兵,B
        ///提克斯塔,B
        ///翼肢鲎 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Hunting_List {
            get {
                return ResourceManager.GetString("Hunting_List", resourceCulture);
            }
        }
    }
}
